import { 
    getCurrentUserProfile, 
    getUserTopTracks, 
    getRecommendations, 
    createPlaylist, 
    addTracksToPlaylist 
} from '../lib/spotify';

// Mapping user moods to Spotify's Audio Features
const MoodAudioFeatures = {
    'Calm': {
        target_acousticness: 0.9,
        target_energy: 0.3,
        target_valence: 0.5,
        target_tempo: 80,
    },
    'Uplift': {
        target_acousticness: 0.2,
        target_energy: 0.8,
        target_valence: 0.9,
        target_tempo: 125,
    },
    'Focus': {
        target_energy: 0.5,
        target_valence: 0.3,
        min_instrumentalness: 0.8,
    }
};

export async function generateMoodPlaylist(moodKey) {
    if (!MoodAudioFeatures[moodKey]) {
        throw new Error(`Mood '${moodKey}' is not supported.`);
    }

    // 1. Get user ID and their top 5 favorite tracks
    const [profile, topTracksResponse] = await Promise.all([
        getCurrentUserProfile(),
        getUserTopTracks(5),
    ]);

    const userId = profile.id;
    const seedTracks = topTracksResponse.items.map(track => track.id);
    const playlistName = `Aurael: ${moodKey} Focus`;

    // 2. Get 50 track recommendations
    const recommendationsResponse = await getRecommendations(
        seedTracks, 
        MoodAudioFeatures[moodKey]
    );

    const trackUris = recommendationsResponse.tracks.map(track => track.uri);

    if (trackUris.length === 0) return null;

    // 3. Create the new private playlist
    const newPlaylist = await createPlaylist(
        userId, 
        playlistName, 
        `A personalized playlist for a ${moodKey} mood, generated by Aurael.`
    );

    // 4. Add the tracks
    await addTracksToPlaylist(newPlaylist.id, trackUris);

    return newPlaylist;
}
